---
- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
  when: ansible_os_family == "Debian"

- name: Create app directory
  file:
    path: /home/{{ ansible_user }}/app/src
    state: directory
    mode: '0755'

- name: Copy Dockerfile
  copy:
    src: Dockerfile
    dest: /home/{{ ansible_user }}/app/Dockerfile

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/app/docker-compose.yml

- name: Copy application source files
  copy:
    src: src/
    dest: /home/{{ ansible_user }}/app/src/

- name: Generate Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /home/{{ ansible_user }}/app/nginx.conf

- name: Start application using Docker Compose
  command: docker-compose up -d
  args:
    chdir: /home/{{ ansible_user }}/app
